### ISSUE TITLE
BlobService was renamed to BlockBlobService in azure.storage 0.33.0

### ISSUE THREAD

**Issue by JrtPec** [michiya/azure-storage-logging#2]
BlobService seems to have been rewritten.
What I've gathered so far:
- BlobService was renamed/split into BlockBlobService, AppendBlobService, PageBlobService
- `put_block_blob_from_path` does not exist anymore, there is however `put_block`

Could you investigate? Are you still maintaining this code?

I will see if I can come up with a (temporary) workaround.

**Comment by michiya** [comment]
Thank you for the contribution! I have merged the PR #3 and pushed it to PyPI as a part of the new version of the package. I hope I can add other new features of azure-storage 0.33 such as Append Blob, custom domain and so on to azure-storage-logging in the near future.
